### ISSUE TITLE
Add documentation: public API, usage examples

### ISSUE THREAD

**Issue by calixteman** [mozilla-releng/mozilla-version#2]

**Comment by JohanLorenzo** [comment]
Thank you for filing the very first issue of mozilla-version :tada:. Good news first: Version 0.1.x already exposes these value via:

``` py 
version.major_number
version.minor_number
version.patch_number
version.beta_number
```

I know it's not crystal clear from the code. These public attributes are set at https://github.com/mozilla-releng/mozilla-version/blob/49a439a82b6af78007d387e3d968556f925f1821/mozilla_version/firefox.py#L56. Your issue points to another problem: There is no public documentation. I'll handle this part. In the meantime, I'm renaming this issue to reflect this lack.

**Comment by JohanLorenzo** [comment]
Documentation now lives at https://mozilla-version.readthedocs.io/en/latest/mozilla_version.html
