### ISSUE TITLE
add dry runs methods to bump versions in order to better check if versions are successive

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/mozilla-version#62]
When we moved nightlies on ESR, there have been some nightly-version related operations that had to be ported in a bunch of places across our projects, including bouncerscript. 

@JohanLorenzo and I agreed that some of the operations that were duplicated in [here](https://github.com/mozilla-releng/bouncerscript/pull/65/files#r307352405) should be made more accessible in this module directly.

This is to track the move of the `check_versions_are_successive` function directly in this module. 

Once that is added here, we should revisit bouncerscript logic as well to simplify it 👍

**Comment by MihaiTabara** [comment]
The methods we add in here should maybe handle ESR cuts as well, even if those happen every {7,8} releases. Otherwise, checks like [this](https://github.com/mozilla-releng/bouncerscript/pull/65/files#diff-044fa19af33620e103b98d4a209ecd6bR174) will fail.

**Comment by JohanLorenzo** [comment]
Done in https://github.com/mozilla-releng/mozilla-version/pull/63
