### ISSUE TITLE
ReadtheDocs Build Failing

### ISSUE THREAD

**Issue by Callek** [mozilla-releng/mozilla-version#72]
This seems to be failing due to looking for `requirements-docs.txt` -- can you fix and/or add me as a maintainer please?

https://readthedocs.org/projects/mozilla-version/

**Comment by JohanLorenzo** [comment]
Thank you very much for noticing these 2 issues! I've just granted you the maintainer role. I was the only one listed 😅 Could you see if you have enough rights to change the `requirements` file location?

**Comment by jcristau** [comment]
Builds are working now.
